/// Flutter icons ActiveIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ActiveIcons
///      fonts:
///       - asset: fonts/ActiveIcons.ttf
///
///
///
library;

import 'package:flutter/widgets.dart';

class ActiveIcons {
  ActiveIcons._();

  static const _kFontFam = 'ActiveIcons';
  static const String? _kFontPkg = null;

  static const IconData favourite = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
